### ISSUE TITLE
how to generate data/input/regions/***.mat?

### ISSUE THREAD

**Issue by Hjy20255** [nightrome/cocostuff10k#1]
hi~
I download the code of SLIC_mex.
i run the code of SLIC_mex successfully.
but how to generate data/input/regions/***.mat?

my software:matlabR2016a

**Comment by nightrome** [comment]
Hi,
thanks for you interest. I assume you would like to use our stuff annotation tool to annotate another dataset?
If you just want to see two example files, you can use those from here: [https://github.com/nightrome/cocostuff/tree/master/annotator/data/input/regions/slico-1000](https://github.com/nightrome/cocostuff/tree/master/annotator/data/input/regions/slico-1000)
So far the script for the generation of the regions was not included in the repository. I have now added it ( https://github.com/nightrome/cocostuff/blob/master/annotator/code/extractSuperpixels.m ). Just run "git pull" to get it.

Note that I still do not provide the script to include existing thing annotations from COCO, because it requires several GB of data. If you need that, give me a shout.

**Comment by Hjy20255** [comment]
thank  you  very  much!!!

**Comment by nightrome** [comment]
Hi,
in case you are interested. The latest version of the code now also includes an extractThings [1] function that retrieves the label maps from COCO.

[1] [https://github.com/nightrome/cocostuff/blob/master/annotator/code/extractThings.m](https://github.com/nightrome/cocostuff/blob/master/annotator/code/extractThings.m)
